services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: releasepilot-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  postgres:
    image: postgres:16
    container_name: releasepilot-postgres
    environment:
      POSTGRES_USER: releasepilot
      POSTGRES_PASSWORD: releasepilot
      POSTGRES_DB: releasepilot
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  promotions-db-setup:
    image: postgres:16
    container_name: releasepilot-promotions-db-setup
    depends_on:
      - postgres
    environment:
      PGPASSWORD: releasepilot
    volumes:
      - ./sql/api:/docker-entrypoint-initdb.d:ro
    command: >
      sh -c "until pg_isready -h postgres -p 5432 -U releasepilot; do sleep 1; done &&
      for f in /docker-entrypoint-initdb.d/*.sql; do
      psql -h postgres -U releasepilot -d releasepilot -v ON_ERROR_STOP=1 -f \"$$f\"; done"

  api:
    build:
      context: ./src
      dockerfile: ReleasePilot.Api/Dockerfile
    container_name: releasepilot-api
    depends_on:
      - rabbitmq
      - postgres
      - promotions-db-setup
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__UserName: guest
      RabbitMq__Password: guest
      RabbitMq__VirtualHost: /
      RabbitMq__PromotionExchange: releasepilot.promotions
      RabbitMq__PromotionRoutingKeyPrefix: promotion
      PromotionRepository__ConnectionString: Host=postgres;Port=5432;Database=releasepilot;Username=releasepilot;Password=releasepilot
    ports:
      - "5252:8080"

  outbox-publisher:
    build:
      context: ./src
      dockerfile: ReleasePilot.OutboxPublisher/Dockerfile
    container_name: releasepilot-outbox-publisher
    depends_on:
      - rabbitmq
      - postgres
      - promotions-db-setup
    environment:
      PromotionRepository__ConnectionString: Host=postgres;Port=5432;Database=releasepilot;Username=releasepilot;Password=releasepilot
      RabbitMq__HostName: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__UserName: guest
      RabbitMq__Password: guest
      RabbitMq__VirtualHost: /
      RabbitMq__PromotionExchange: releasepilot.promotions
      RabbitMq__PromotionRoutingKeyPrefix: promotion
      OutboxPublisher__PollIntervalSeconds: 3
      OutboxPublisher__BatchSize: 50
      OutboxPublisher__RetryDelaySeconds: 10
      OutboxPublisher__MaxRetryCount: 10

  audit-worker:
    build:
      context: ./src
      dockerfile: ReleasePilot.AuditWorker/Dockerfile
    container_name: releasepilot-audit-worker
    depends_on:
      - rabbitmq
      - postgres
    environment:
      AuditWorker__Postgres__ConnectionString: Host=postgres;Port=5432;Database=releasepilot;Username=releasepilot;Password=releasepilot
      AuditWorker__RabbitMq__HostName: rabbitmq
      AuditWorker__RabbitMq__Port: 5672
      AuditWorker__RabbitMq__UserName: guest
      AuditWorker__RabbitMq__Password: guest
      AuditWorker__RabbitMq__VirtualHost: /
      AuditWorker__RabbitMq__PromotionExchange: releasepilot.promotions
      AuditWorker__RabbitMq__AuditQueueName: releasepilot.audit
      AuditWorker__RabbitMq__AuditBindingKey: promotion.#

volumes:
  postgres_data:
